pipeline {
    agent any
    tools {
        maven "maven-3.9.7"
    }
    stages {
        stage('Check for Changes') {
            steps {
                script {
                    def changes = bat(script: 'git diff --name-only HEAD~1 HEAD', returnStdout: true).trim()
                    if (changes.contains("LaboMicroServices/Service-Laboratoire/")) {
                        echo "Changes detected in LaboMicroServices/Service-Laboratoire. Continuing with the build."
                        currentBuild.description = "CHANGED"
                    } else {
                        echo "No changes detected in LaboMicroServices/Service-Laboratoire. Marking build as successful without further action."
                        currentBuild.result = 'SUCCESS'
                    }
                }
            }
        }

        stage('Checkout Code') {
            when {
                expression { currentBuild.description == "CHANGED" }
            }
            steps {
                bat 'git pull origin master'
            }
        }

        stage('SonarQube Analysis') {
            when {
                expression { currentBuild.description == "CHANGED" }
            }
            steps {
                withSonarQubeEnv('SonarQube') {
                    dir('LaboMicroServices/Service-Laboratoire') {
                        bat 'mvn sonar:sonar'
                    }
                }
            }
        }

        stage('Build and Test Laboratoire Service') {
            when {
                expression { currentBuild.description == "CHANGED" }
            }
            steps {
                dir('LaboMicroServices/Service-Laboratoire') {
                    bat 'mvn clean install -DskipTests=false'
                }
            }
        }

        stage('Build Docker Image') {
            when {
                expression { currentBuild.description == "CHANGED" }
            }
            steps {
                dir('LaboMicroServices/Service-Laboratoire') {
                    bat 'docker build -t artistefx/service-laboratoire:latest .'
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            when {
                expression { currentBuild.description == "CHANGED" }
            }
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-artistefx', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                    script {
                        bat 'docker login -u %DOCKERHUB_USERNAME% -p %DOCKERHUB_PASSWORD%'
                        bat "docker push artistefx/service-laboratoire:latest"
                    }
                }
            }
        }

        stage('Deploy to Minikube') {
            when {
                expression { currentBuild.description == "CHANGED" }
            }
            steps {
                withCredentials([string(credentialsId: 'kubeconf', variable: 'KUBECONFIG_PATH')]) {
                    script {
                        bat "kubectl --kubeconfig=%KUBECONFIG_PATH% apply -f k8s/Service-Laboratoire-Deployment.yaml"
                        bat "kubectl --kubeconfig=%KUBECONFIG_PATH% rollout restart deployment service-laboratoire"
                    }
                }
            }
        }
    }
    post {
        success {
            script {
                if (currentBuild.description != "CHANGED") {
                    echo 'No changes to build. Job marked as successful without build steps.'
                }
            }
        }
    }
}
