server:
  port: 8089
spring:
  application:
    name: Analyses
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/serviceanalyses
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true