apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: artistehmz/labo-backend:latest # Use the appropriate image tag
          ports:
            - containerPort: 8080  # Replace with your backend's actual port
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080  # Replace with your backend's actual port
      targetPort: 8080  # Replace with your backend's actual port
