apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-utilisateurs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-utilisateurs
  template:
    metadata:
      labels:
        app: service-utilisateurs
    spec:
      containers:
        - name: service-utilisateurs
          image: artistefx/service-utilisateurs:latest  # Make sure this matches
          ports:
            - containerPort: 8080  # Your service port
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: service-utilisateurs
spec:
  selector:
    app: service-utilisateurs
  ports:
    - protocol: TCP
      port: 80         # Port exposed by the service
      targetPort: 8080 # Port on which the container is listening
      name: http
  type: ClusterIP