apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-analyses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-analyses
  template:
    metadata:
      labels:
        app: service-analyses
    spec:
      containers:
        - name: service-analyses
          image: artistefx/service-analyses  # Make sure this matches
          ports:
            - containerPort: 8080  # Your service port
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: service-analyses
spec:
  selector:
    app: service-analyses
  ports:
    - protocol: TCP
      port: 80         # Port exposed by the service
      targetPort: 8080 # Port on which the container is listening
      name: http
  type: ClusterIP
