server:
  port: 8088
spring:
  application:
    name: customer
  datasource:
    password: 123456
    url: jdbc:mysql://mysql-service:3306/serviceLaboratoire
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
